### ISSUE TITLE
Expand readme ?

### ISSUE THREAD

**Issue by ozh** [adigitalife/yourls-allow-aliases#1]
Hey @adigitalife, nice to see you gave your plugin a proper repo (any other old stuff to migrate to github maybe?)

You should probably consider expanding a bit the readme, giving a few examples. The old Google Code repo had a short readme, and the first issue was providing good insight too: https://code.google.com/archive/p/yourls-allow-aliases/issues/1

When you have some time :)

Cheers,

Ozh

**Comment by adigitalife** [comment]
Good point!  I didn't even realize that there were any issues with the plugin.  On my site it works with I think at least 5 aliases.  I think the plugin should just work out of the box but I'll try to setup a clean YOURLS site to test the plugin to be sure.

Also, I'll check if there are any other plugins I should upload to github.

**Comment by adigitalife** [comment]
OK, I hope the readme is now a bit better.
