### ISSUE TITLE
DNS configuration

### ISSUE THREAD

**Issue by kapiljhajhria** [adigitalife/yourls-allow-aliases#5]
Hi, i have two domains 
domain01.com and domain02.com

i have installed and using YOURLs at domain01.com/yourls

i want the all the links that i shortned using domain01 for exampe
domain01.com/yourls/abcd to also works as domain02.com/abcd

i believe this plugin can do that. but there is no instructons on how to confugre DNS of domain02.com for the plugin to work.

**Comment by adigitalife** [comment]
DNS configuration is outside the scope of this plugin.  It is assumed that both domain01.com and domain02.com are already pointing to the same IP address.  If this is not the case, then you need to sort that out first before the plugin will work.

By the way, domain01.com/yourls/abcd will work as domain02.com/yourls/abcd and not domain02.com/abcd.
